/*
 * Filename: pa4Globals.c
 * Date: 02/28/2019
 *
 * Global file for the assembly functions to access constants.
 *
 * XXX: DO NOT EDIT THIS FILE
 * (you do NOT need to add your own file header)
 */

#include "pa4.h"

// Offsets of gramNode struct memebers.
int INDEX_OFFSET_G = offsetof( gramNode_t, index );
int COUNT_OFFSET_G = offsetof( gramNode_t, count );
int NEXT_OFFSET_G  = offsetof( gramNode_t, next  );

// Offsets of vocab struct members.
int WORDS_OFFSET_G    = offsetof( vocab_t, words    );
int NUMWORDS_OFFSET_G = offsetof( vocab_t, numWords );
